version: '1.0'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - wordpress-network1

  neo4j:
    image: 'bitnami/neo4j:latest'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/bitnami/neo4j/data
    networks:
      - wordpress-network1
    
  wordpress:
    image: 'bitnami/wordpress:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - wordpress-network1
    depends_on:
      - mariadb

networks:
  wordpress-network1:

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  neo4j_data:
    driver: local
